/**
 * Walks a project's wit/ directory, parses each .wit file, and emits
 * `gen/<file>.d.ts` files with TypeScript types for every named record,
 * enum, variant, and flags.
 *
 * Mirror of `astrid_sdk_macros::wit_events::generate` (Rust). Naming:
 *   - kebab-case names → PascalCase in TS (matching the Rust output's
 *     PascalCase struct names).
 *   - kebab-case field names → snake_case (matching Rust's
 *     `#[serde(rename_all = "snake_case")]` on generated structs, so the
 *     wire format is identical regardless of which SDK produced it).
 *   - option<T> → T | undefined (with optional `?:` field syntax).
 *   - list<T> → T[].
 *   - tuple<T,U,...> → [T, U, ...].
 *   - variants → discriminated unions with `tag` + optional `value`.
 *   - flags → string-array of variant names.
 */

import { parseWit } from "./wit-parser.mjs";
import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import { join, basename, extname } from "node:path";

export async function codegenWitEvents(projectDir) {
  const witDir = join(projectDir, "wit");
  let entries;
  try {
    entries = await readdir(witDir, { withFileTypes: true });
  } catch (err) {
    if (err.code === "ENOENT") return { files: 0, types: 0 };
    throw err;
  }

  const witFiles = entries
    .filter((e) => e.isFile() && extname(e.name) === ".wit")
    .map((e) => join(witDir, e.name));

  if (witFiles.length === 0) return { files: 0, types: 0 };

  const genDir = join(projectDir, "gen");
  await mkdir(genDir, { recursive: true });

  let totalTypes = 0;
  for (const witPath of witFiles) {
    const source = await readFile(witPath, "utf8");
    const ast = parseWit(source, witPath);
    const ts = emitTs(ast);
    const baseName = basename(witPath, ".wit");
    const outPath = join(genDir, `${baseName}.d.ts`);
    await writeFile(outPath, ts);
    totalTypes += ast.interfaces.reduce((sum, iface) => sum + iface.types.length, 0);
  }

  return { files: witFiles.length, types: totalTypes };
}

function emitTs(ast) {
  const lines = [
    "// Auto-generated by @astrid-os/build from a WIT file. Do not edit by hand.",
    "// Mirror of `astrid_sdk_macros::wit_events!` output.",
    "",
  ];

  // Per-interface namespacing prevents collisions across the canonical
  // interface set — agent / approval / elicit all define `record
  // response`, and all three must be addressable. Build an owner index
  // so cross-interface references can fully qualify
  // (e.g. `types.Message` inside the `llm` namespace).
  const typeOwner = new Map();
  for (const iface of ast.interfaces) {
    for (const t of iface.types) {
      typeOwner.set(t.name, kebabToSnake(iface.name));
    }
  }

  for (const iface of ast.interfaces) {
    const ns = kebabToSnake(iface.name);
    lines.push(`/** Types generated from the \`${iface.name}\` WIT interface. */`);
    lines.push(`export namespace ${ns} {`);
    for (const t of iface.types) {
      if (t.doc) emitDoc(lines, t.doc, "  ");
      if (t.kind === "record") emitRecord(lines, t, typeOwner, ns);
      else if (t.kind === "enum") emitEnum(lines, t);
      else if (t.kind === "variant") emitVariant(lines, t, typeOwner, ns);
      else if (t.kind === "flags") emitFlags(lines, t);
      lines.push("");
    }
    lines.push(`}`);
    lines.push("");
  }

  return lines.join("\n");
}

function emitRecord(lines, t, typeOwner, currentNs) {
  lines.push(`  export interface ${kebabToPascal(t.name)} {`);
  for (const f of t.fields) {
    if (f.doc) emitDoc(lines, f.doc, "    ");
    const fieldName = kebabToSnake(f.name);
    const isOption = f.type.kind === "option";
    const renderedType = renderType(isOption ? f.type.inner : f.type, typeOwner, currentNs);
    if (isOption) {
      lines.push(`    ${fieldName}?: ${renderedType};`);
    } else {
      lines.push(`    ${fieldName}: ${renderedType};`);
    }
  }
  lines.push(`  }`);
}

function emitEnum(lines, t) {
  const variants = t.cases.map((c) => JSON.stringify(kebabToSnake(c.name))).join(" | ");
  lines.push(`  export type ${kebabToPascal(t.name)} = ${variants};`);
}

function emitVariant(lines, t, typeOwner, currentNs) {
  // Mirror serde(tag = "tag", content = "value") — see wit_events.rs
  // line 113. Wire format: `{ tag: "case-name", value?: T }`.
  const cases = t.cases.map((c) => {
    const tag = kebabToSnake(c.name);
    if (c.type === undefined) return `{ tag: ${JSON.stringify(tag)} }`;
    return `{ tag: ${JSON.stringify(tag)}; value: ${renderType(c.type, typeOwner, currentNs)} }`;
  });
  lines.push(`  export type ${kebabToPascal(t.name)} =`);
  for (let i = 0; i < cases.length; i++) {
    lines.push(`    | ${cases[i]}${i === cases.length - 1 ? ";" : ""}`);
  }
}

function emitFlags(lines, t) {
  // Mirror the Rust output: `type X = Vec<XFlag>;` becomes
  // `type X = XFlag[]; type XFlag = "case" | ...`.
  const flagName = kebabToPascal(t.name) + "Flag";
  const flagUnion = t.cases.map((c) => JSON.stringify(kebabToSnake(c.name))).join(" | ");
  lines.push(`  export type ${flagName} = ${flagUnion};`);
  lines.push(`  export type ${kebabToPascal(t.name)} = ${flagName}[];`);
}

function renderType(ty, typeOwner, currentNs) {
  switch (ty.kind) {
    case "builtin":
      return renderBuiltin(ty.name);
    case "option":
      return `${renderType(ty.inner, typeOwner, currentNs)} | undefined`;
    case "list":
      return `${renderType(ty.inner, typeOwner, currentNs)}[]`;
    case "tuple":
      return `[${ty.elems.map((e) => renderType(e, typeOwner, currentNs)).join(", ")}]`;
    case "named": {
      const pascal = kebabToPascal(ty.name);
      // If the type lives in another interface, fully qualify so the
      // reference resolves under the parent module instead of looking
      // for it inside the current namespace.
      const owner = typeOwner && typeOwner.get(ty.name);
      if (owner && owner !== currentNs) return `${owner}.${pascal}`;
      return pascal;
    }
    case "unknown":
      return "unknown";
    default:
      return "unknown";
  }
}

function renderBuiltin(name) {
  switch (name) {
    case "bool":
      return "boolean";
    case "string":
    case "char":
      return "string";
    case "u8":
    case "u16":
    case "u32":
    case "s8":
    case "s16":
    case "s32":
    case "f32":
    case "f64":
      return "number";
    case "u64":
    case "s64":
      // 64-bit integers cross the WIT boundary as bigint in jco bindings.
      return "bigint";
    default:
      return "unknown";
  }
}

function kebabToPascal(s) {
  return s
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

function kebabToSnake(s) {
  return s.replace(/-/g, "_");
}

function emitDoc(lines, doc, indent = "") {
  const docLines = doc.split("\n");
  if (docLines.length === 1) {
    lines.push(`${indent}/** ${docLines[0]} */`);
    return;
  }
  lines.push(`${indent}/**`);
  for (const dl of docLines) lines.push(`${indent} * ${dl}`);
  lines.push(`${indent} */`);
}
