// Auto-generated by @astrid-os/build from a WIT file. Do not edit by hand.
// Mirror of `astrid_sdk_macros::wit_events!` output.

/** A conversation message. */
export interface Message {
  role: MessageRole;
  content: MessageContent;
}

/** Message role. */
export type MessageRole = "system" | "user" | "assistant" | "tool";

/**
 * Message content — text, tool calls, tool results, or mixed.
 * 
 * Note: the Rust type uses #[serde(untagged)] so there is no type
 * discriminant on the wire. This variant is for schema documentation.
 */
export type MessageContent =
  | { tag: "text"; value: string }
  | { tag: "tool_calls"; value: ToolCall[] }
  | { tag: "tool_result"; value: ToolCallResult }
  | { tag: "multi_part"; value: ContentPart[] };

/**
 * A part of multi-part content.
 * 
 * Note: Rust uses #[serde(tag = "type", rename_all = "snake_case")]
 * so the wire format is {"type": "text", "text": "..."} or
 * {"type": "image", "data": "...", "media_type": "..."}.
 */
export type ContentPart =
  | { tag: "text"; value: string }
  | { tag: "image"; value: ImageData };

/** Image data embedded in a content part. */
export interface ImageData {
  /** Base64-encoded image data. */
  data: string;
  /** MIME type (e.g. "image/png"). */
  media_type: string;
}

/** A tool call requested by the model. */
export interface ToolCall {
  /** Tool call identifier. */
  id: string;
  /** Name of the tool to invoke. */
  name: string;
  /** JSON-encoded arguments (parsed as serde_json::Value in Rust). */
  arguments: string;
}

/** Result of executing a tool call. */
export interface ToolCallResult {
  /** The tool call this result corresponds to. */
  call_id: string;
  /** Result content (text). */
  content: string;
  /** Whether the tool execution failed. */
  is_error: boolean;
}

/** A tool definition provided to the model. */
export interface ToolDefinition {
  /** Tool name. */
  name: string;
  /** Human-readable description. */
  description?: string;
  /** JSON Schema for the tool's input (parsed as serde_json::Value in Rust). */
  input_schema: string;
}

/** Token usage statistics. */
export interface Usage {
  /** Number of input tokens consumed. */
  input_tokens: bigint;
  /** Number of output tokens generated. */
  output_tokens: bigint;
}

/** An available LLM provider entry. */
export interface ProviderEntry {
  /** Model ID (e.g. "gpt-5.4", "claude-sonnet-4-20250514"). */
  id: string;
  /** Human-readable description. */
  description: string;
  /** IPC topic to publish LLM requests to. */
  request_topic: string;
  /** IPC topic the provider streams responses on. */
  stream_topic: string;
  /** Model capabilities (e.g. "text", "vision", "tools"). */
  capabilities: string[];
  /** Provider's context window size in tokens. */
  context_window?: bigint;
  /** Provider's max output tokens per request. */
  max_output_tokens?: bigint;
}

/** Request to generate a response (IpcPayload::LlmRequest). */
export interface GenerateRequest {
  /** Unique request identifier (UUID as string). */
  request_id: string;
  /** Target model identifier. */
  model: string;
  /** Conversation messages. */
  messages: Message[];
  /** Tool definitions available to the model. */
  tools: ToolDefinition[];
  /** System prompt. */
  system: string;
}

/**
 * A streaming event from the provider.
 * 
 * Note: Rust uses default externally-tagged enum (PascalCase variant
 * names). Wire format: {"TextDelta": "..."}, {"ToolCallStart": {...}}.
 */
export type StreamEvent =
  | { tag: "text_delta"; value: string }
  | { tag: "tool_call_start"; value: ToolCallStartEvent }
  | { tag: "tool_call_delta"; value: ToolCallDeltaEvent }
  | { tag: "tool_call_end"; value: ToolCallEndEvent }
  | { tag: "reasoning_delta"; value: string }
  | { tag: "usage"; value: Usage }
  | { tag: "done" }
  | { tag: "error"; value: string };

export interface ToolCallStartEvent {
  id: string;
  name: string;
}

export interface ToolCallDeltaEvent {
  id: string;
  args_delta: string;
}

export interface ToolCallEndEvent {
  id: string;
}

/** Final (non-streaming) response. */
export interface GenerateResponse {
  message: Message;
  has_tool_calls: boolean;
  stop_reason: StopReason;
  usage: Usage;
}

/**
 * Reason the model stopped generating.
 * 
 * Note: Rust uses default externally-tagged enum (PascalCase).
 * Wire values: "EndTurn", "MaxTokens", "ToolUse", "StopSequence".
 */
export type StopReason = "end_turn" | "max_tokens" | "tool_use" | "stop_sequence";

/** Request to fetch conversation history. */
export interface GetMessagesRequest {
  session_id: string;
  correlation_id: string;
  append_before_read?: Message[];
}

/** Response containing conversation history. */
export interface GetMessagesResponse {
  correlation_id: string;
  messages: Message[];
}

/** Request to clear a session and start fresh. */
export interface ClearRequest {
  session_id: string;
  correlation_id: string;
}

/** Response confirming session cleared. */
export interface ClearResponse {
  correlation_id: string;
  new_session_id: string;
  old_session_id: string;
}

/** Fire-and-forget append to conversation history. */
export interface AppendRequest {
  session_id: string;
  messages: Message[];
}

/** Request to build the agent's system prompt. */
export interface BuildRequest {
  workspace_root: string;
  session_id?: string;
}

/** Response with the assembled system prompt. */
export interface BuildResponse {
  prompt: string;
  session_id?: string;
}

/** Request to compact messages within a token budget. */
export interface CompactRequest {
  session_id: string;
  /** Current conversation messages. */
  messages: Message[];
  max_tokens: bigint;
  target_tokens: bigint;
}

/** Result of compaction. */
export interface CompactResponse {
  /** Messages after compaction. */
  messages: Message[];
  compacted: boolean;
  messages_removed: number;
  strategy: string;
}

/** Request to estimate token count. */
export interface EstimateRequest {
  /** Messages to estimate token count for. */
  messages: Message[];
}

/** Token count estimate. */
export interface EstimateResponse {
  estimated_tokens: bigint;
}

/** Hook payload sent before compaction. */
export interface BeforeCompactionHook {
  session_id: string;
  /** Current messages. */
  messages: Message[];
  message_count: number;
  estimated_tokens: bigint;
  max_tokens: bigint;
  response_topic: string;
}

/**
 * Plugin response to before-compaction hook.
 * 
 * Note: Rust uses #[serde(rename_all = "camelCase")] so wire field
 * names are camelCase: pinnedMessageIds, customStrategy.
 */
export interface BeforeCompactionHookResponse {
  skip?: boolean;
  pinned_message_ids: string[];
  custom_strategy?: string;
}

/** Notification after compaction completes. */
export interface AfterCompactionEvent {
  session_id: string;
  messages_before: number;
  messages_after: number;
  tokens_before: bigint;
  tokens_after: bigint;
  strategy_used: string;
}

/** Request to assemble a prompt for LLM generation. */
export interface AssembleRequest {
  /** Conversation messages. */
  messages: Message[];
  system_prompt: string;
  request_id: string;
  model: string;
  provider: string;
  session_id?: string;
}

/** Assembled prompt ready for LLM. */
export interface AssembleResponse {
  system_prompt: string;
  user_context_prefix: string;
  request_id: string;
  session_id?: string;
  /** Collected tool schemas from tool-providing capsules. */
  tools: ToolDefinition[];
  /** Session conversation history messages. */
  messages: Message[];
}

/** Hook payload sent before prompt build. */
export interface BeforeBuildHook {
  messages: Message[];
  system_prompt: string;
  request_id: string;
  model: string;
  provider: string;
  response_topic: string;
}

/**
 * Plugin response to before-build hook.
 * 
 * Note: Rust uses #[serde(rename_all = "camelCase")] so wire field
 * names are camelCase: prependSystemContext, appendSystemContext, etc.
 */
export interface BeforeBuildHookResponse {
  prepend_system_context?: string;
  append_system_context?: string;
  system_prompt?: string;
  prepend_context?: string;
}

/** Notification after prompt is built. */
export interface AfterBuildEvent {
  system_prompt: string;
  user_context_prefix: string;
  request_id: string;
}

/** Request to cancel in-flight tool executions. */
export interface CancelRequest {
  call_ids: string[];
}

/** Lifecycle events emitted by the kernel. */
export type LifecycleEvent = "session_created" | "session_ended" | "tool_call_started" | "tool_call_completed" | "tool_result_persisting" | "message_received" | "message_sending" | "message_sent" | "sub_agent_spawned" | "sub_agent_completed" | "sub_agent_failed" | "sub_agent_cancelled" | "context_compaction_started" | "context_compaction_completed" | "kernel_started" | "kernel_shutdown";

/** Merged result from hook fan-out. */
export interface HookResult {
  /** Whether the operation should be skipped. */
  skip?: boolean;
  /** Merged data from interceptor responses (opaque JSON). */
  data?: string;
}
