// Auto-generated by @astrid-os/build from a WIT file. Do not edit by hand.
// Mirror of `astrid_sdk_macros::wit_events!` output.

/** Types generated from the `types` WIT interface. */
export namespace types {
  /** A conversation message. */
  export interface Message {
    role: MessageRole;
    content: MessageContent;
  }

  export type MessageRole = "system" | "user" | "assistant" | "tool";

  /** Message content — text, tool calls, tool results, or mixed. */
  export type MessageContent =
    | { tag: "text"; value: string }
    | { tag: "tool_calls"; value: ToolCall[] }
    | { tag: "tool_result"; value: ToolCallResult }
    | { tag: "multi_part"; value: ContentPart[] };

  export type ContentPart =
    | { tag: "text"; value: string }
    | { tag: "image"; value: ImageData };

  export interface ImageData {
    data: string;
    media_type: string;
  }

  /** A tool call requested by the model. */
  export interface ToolCall {
    /** Tool call identifier. */
    id: string;
    /** Name of the tool to invoke. */
    name: string;
    /** JSON-encoded arguments (serde_json::Value in Rust). */
    arguments: string;
  }

  /** Result of executing a tool call. */
  export interface ToolCallResult {
    call_id: string;
    content: string;
    is_error: boolean;
  }

  /** A tool definition provided to the model. */
  export interface ToolDefinition {
    name: string;
    description?: string;
    input_schema: string;
  }

  /** Token usage statistics. */
  export interface Usage {
    input_tokens: bigint;
    output_tokens: bigint;
  }

}

/** Types generated from the `agent` WIT interface. */
export namespace agent {
  /** A response generated by the agent for the user. */
  export interface Response {
    /** The text output (may be a streaming delta or a complete reply). */
    text: string;
    /** True if this is the final response in the turn. */
    is_final: boolean;
    /** Session ID for multi-session attribution. */
    session_id: string;
  }

  /**
   * Notification that the active session has changed (e.g. cleared,
   * branched, restored). Uplinks use this to refresh their view.
   */
  export interface SessionChanged {
    /** The session ID that is now active. */
    session_id: string;
    /** Optional ID of the session that was previously active. */
    previous_session_id?: string;
    /** Reason for the change (e.g. "clear", "restore", "branch"). */
    reason: string;
  }

}

/** Types generated from the `approval` WIT interface. */
export namespace approval {
  /** An interceptor or capsule request for human authorization. */
  export interface Required {
    /** Correlation ID matching the response. */
    request_id: string;
    /** The action being requested (e.g. `"git push"`). */
    action: string;
    /** The resource target (e.g. full command string). */
    target_resource: string;
    /** Justification shown to the user. */
    reason: string;
  }

  /** Response to an approval request. */
  export interface Response {
    /** Must match the `request-id` from the originating request. */
    request_id: string;
    /**
     * The user's decision (e.g. `"approve"`, `"deny"`,
     * `"approve_session"`, `"approve_always"`, `"allowance"`).
     */
    decision: string;
    /** Optional reason for the decision. */
    reason?: string;
  }

}

/** Types generated from the `client` WIT interface. */
export namespace client {
  /** A client has connected to an uplink. */
  export interface Connect {
    /** Optional client identifier (e.g. process name + PID). */
    client_id?: string;
  }

  /** A client is disconnecting gracefully. */
  export interface Disconnect {
    /** Optional reason for disconnection (e.g. "quit", "timeout"). */
    reason?: string;
  }

}

/** Types generated from the `context` WIT interface. */
export namespace context {
  /** Request to compact messages within a token budget. */
  export interface CompactRequest {
    session_id: string;
    messages: types.Message[];
    max_tokens: bigint;
    target_tokens: bigint;
  }

  /** Result of compaction. */
  export interface CompactResponse {
    messages: types.Message[];
    compacted: boolean;
    messages_removed: number;
    strategy: string;
  }

  /** Request to estimate token count for messages. */
  export interface EstimateRequest {
    messages: types.Message[];
  }

  /** Token count estimate. */
  export interface EstimateResponse {
    estimated_tokens: bigint;
  }

  /** Hook payload sent before compaction (plugins can influence). */
  export interface BeforeCompactionHook {
    session_id: string;
    messages: types.Message[];
    message_count: number;
    estimated_tokens: bigint;
    max_tokens: bigint;
    response_topic: string;
  }

  /** Plugin response to before-compaction hook. */
  export interface BeforeCompactionHookResponse {
    skip?: boolean;
    pinned_message_ids: string[];
    custom_strategy?: string;
  }

  /** Notification after compaction completes. */
  export interface AfterCompactionEvent {
    session_id: string;
    messages_before: number;
    messages_after: number;
    tokens_before: bigint;
    tokens_after: bigint;
    strategy_used: string;
  }

}

/** Types generated from the `elicit` WIT interface. */
export namespace elicit {
  /** A lifecycle hook is requesting user input. */
  export interface Request {
    /** Correlation ID matching the response. */
    request_id: string;
    /** The capsule requesting input. */
    capsule_id: string;
    /** Field descriptor reusing the onboarding schema. */
    field: onboarding.Field;
  }

  /** Response to an elicit request. */
  export interface Response {
    /** Must match the `request-id` from the originating request. */
    request_id: string;
    /** The user's input. Absent if the user cancelled. */
    value?: string;
    /** For `array`-type fields, the collected items. */
    values?: string[];
  }

}

/** Types generated from the `hook` WIT interface. */
export namespace hook {
  /** Lifecycle events emitted by the kernel. */
  export type LifecycleEvent = "session_created" | "session_ended" | "tool_call_started" | "tool_call_completed" | "tool_result_persisting" | "message_received" | "message_sending" | "message_sent" | "sub_agent_spawned" | "sub_agent_completed" | "sub_agent_failed" | "sub_agent_cancelled" | "context_compaction_started" | "context_compaction_completed" | "kernel_started" | "kernel_shutdown";

  /** Merged result from hook fan-out. */
  export interface HookResult {
    /** Whether the operation should be skipped. */
    skip?: boolean;
    /** Merged data from interceptor responses (opaque JSON). */
    data?: string;
  }

}

/** Types generated from the `llm` WIT interface. */
export namespace llm {
  /**
   * Request asking an LLM-provider capsule to describe itself.
   * Topic: `llm.v1.request.describe`. The registry capsule fans this
   * out to discover available providers and their per-provider
   * request / stream topics.
   */
  export interface DescribeRequest {
    /**
     * Correlation ID for the response. The provider replies on
     * `llm.v1.response.describe.<correlation-id>`.
     */
    correlation_id: string;
  }

  /**
   * Provider self-description response.
   * Topic: `llm.v1.response.describe.<correlation-id>`.
   */
  export interface DescribeResponse {
    /** Must match the `correlation-id` from the originating request. */
    correlation_id: string;
    /**
     * Provider entries the capsule offers (one capsule may expose
     * multiple models — e.g. an OpenAI-compatible front-end serving
     * several model IDs).
     */
    providers: registry.ProviderEntry[];
  }

  /** Request to generate a response. */
  export interface GenerateRequest {
    request_id: string;
    model: string;
    messages: types.Message[];
    tools: types.ToolDefinition[];
    /** System prompt. */
    system: string;
  }

  /** A streaming event from the provider. */
  export type StreamEvent =
    | { tag: "text_delta"; value: string }
    | { tag: "tool_call_start"; value: ToolCallStartEvent }
    | { tag: "tool_call_delta"; value: ToolCallDeltaEvent }
    | { tag: "tool_call_end"; value: ToolCallEndEvent }
    | { tag: "reasoning_delta"; value: string }
    | { tag: "usage"; value: types.Usage }
    | { tag: "done" }
    | { tag: "error"; value: string };

  export interface ToolCallStartEvent {
    id: string;
    name: string;
  }

  export interface ToolCallDeltaEvent {
    id: string;
    args_delta: string;
  }

  export interface ToolCallEndEvent {
    id: string;
  }

  /** Final (non-streaming) response. */
  export interface GenerateResponse {
    message: types.Message;
    has_tool_calls: boolean;
    stop_reason: StopReason;
    usage: types.Usage;
  }

  export type StopReason = "end_turn" | "max_tokens" | "tool_use" | "stop_sequence";

}

/** Types generated from the `onboarding` WIT interface. */
export namespace onboarding {
  /** A capsule needs environment variables to be provided by the user. */
  export interface Required {
    /** The ID of the capsule requiring onboarding. */
    capsule_id: string;
    /** Rich field descriptors for each missing env var. */
    fields: Field[];
  }

  /** A field descriptor for capsule onboarding. */
  export interface Field {
    /** The environment variable key. */
    key: string;
    /** The prompt shown to the user. */
    prompt: string;
    /** Optional description for additional context. */
    description?: string;
    /** The input type for this field. */
    field_type: FieldType;
    /** Optional default value. */
    default?: string;
    /** Placeholder hint text shown when the input is empty (e.g. `"sk-..."`). */
    placeholder?: string;
  }

  /** The type of input expected for an onboarding field. */
  export type FieldType =
    | { tag: "text" }
    | { tag: "secret" }
    | { tag: "choice"; value: string[] }
    | { tag: "array" };

}

/** Types generated from the `prompt` WIT interface. */
export namespace prompt {
  /** Request to assemble a prompt for LLM generation. */
  export interface AssembleRequest {
    messages: types.Message[];
    system_prompt: string;
    request_id: string;
    model: string;
    provider: string;
    session_id?: string;
  }

  /** Assembled prompt ready for LLM. */
  export interface AssembleResponse {
    system_prompt: string;
    user_context_prefix: string;
    request_id: string;
    session_id?: string;
    /** Collected tool schemas from tool-providing capsules. */
    tools: types.ToolDefinition[];
    /** Session conversation history messages. */
    messages: types.Message[];
  }

  /** Hook payload sent before prompt build (plugins inject context). */
  export interface BeforeBuildHook {
    messages: types.Message[];
    system_prompt: string;
    request_id: string;
    model: string;
    provider: string;
    response_topic: string;
  }

  /** Plugin response to before-build hook. */
  export interface BeforeBuildHookResponse {
    prepend_system_context?: string;
    append_system_context?: string;
    system_prompt?: string;
    prepend_context?: string;
  }

  /** Notification after prompt is built. */
  export interface AfterBuildEvent {
    system_prompt: string;
    user_context_prefix: string;
    request_id: string;
  }

}

/** Types generated from the `registry` WIT interface. */
export namespace registry {
  /** An available LLM provider entry. */
  export interface ProviderEntry {
    /** Model ID (e.g. "gpt-5.4", "claude-sonnet-4-20250514"). */
    id: string;
    /** Human-readable description. */
    description: string;
    /** IPC topic to publish LLM requests to. */
    request_topic: string;
    /** IPC topic the provider streams responses on. */
    stream_topic: string;
    /** Model capabilities (e.g. "text", "vision", "tools"). */
    capabilities: string[];
    /** Provider's context window size in tokens. */
    context_window?: bigint;
    /** Provider's max output tokens per request. */
    max_output_tokens?: bigint;
  }

  /** A single option in a selection picker. */
  export interface SelectionOption {
    /** Machine-readable identifier sent back on the callback. */
    id: string;
    /** Human-readable label shown in the picker. */
    label: string;
    /** Optional description shown alongside the label. */
    description?: string;
  }

  /**
   * Capsule asking the user to choose from a set of options. Used by
   * the registry to drive the LLM-provider picker UI in the TUI.
   * Topic: `registry.v1.selection.required`.
   */
  export interface SelectionRequired {
    /** Correlation ID for the callback. */
    request_id: string;
    /** Title or prompt shown above the list. */
    title: string;
    /** The selectable options. */
    options: SelectionOption[];
    /** IPC topic to publish the user's choice back on. */
    callback_topic: string;
  }

  /**
   * User's selection sent back to the requesting capsule.
   * Topic: `registry.v1.selection.callback` (or the `callback-topic`
   * declared in the matching `selection-required`).
   */
  export interface SelectionCallback {
    /**
     * Must match the `request-id` from the originating
     * `selection-required`.
     */
    request_id: string;
    /** `id` of the chosen `selection-option`. */
    selected_id: string;
  }

}

/** Types generated from the `session` WIT interface. */
export namespace session {
  /** Request to fetch conversation history. */
  export interface GetMessagesRequest {
    session_id: string;
    correlation_id: string;
    append_before_read?: types.Message[];
  }

  /** Response containing conversation history. */
  export interface GetMessagesResponse {
    correlation_id: string;
    messages: types.Message[];
  }

  /** Request to clear a session and start fresh. */
  export interface ClearRequest {
    session_id: string;
    correlation_id: string;
  }

  /** Response confirming session cleared. */
  export interface ClearResponse {
    correlation_id: string;
    new_session_id: string;
    old_session_id: string;
  }

  /** Fire-and-forget append to conversation history. */
  export interface AppendRequest {
    session_id: string;
    messages: types.Message[];
  }

  /**
   * Broadcast notification that a session was cleared. Distinct from
   * `clear-request`/`clear-response` (the request/response pair the
   * session capsule handles): this is a fan-out event the agent loop
   * publishes after a successful clear so unrelated capsules can drop
   * any per-session ephemeral state. Topic: `session.v1.clear`.
   */
  export interface SessionCleared {
    /** Session ID that was cleared. */
    session_id: string;
  }

}

/** Types generated from the `spark` WIT interface. */
export namespace spark {
  /** Request to build the agent's system prompt. */
  export interface BuildRequest {
    workspace_root: string;
    session_id?: string;
  }

  /** Response with the assembled system prompt. */
  export interface BuildResponse {
    prompt: string;
    session_id?: string;
  }

}

/** Types generated from the `system` WIT interface. */
export namespace system {
  /**
   * Published once after every capsule has reported ready, signalling
   * that the agent stack is fully online. Topic: `astrid.v1.capsules_loaded`.
   */
  export interface CapsulesLoaded {
    /** IDs of every capsule that successfully loaded. */
    capsule_ids: string[];
  }

  /**
   * Periodic kernel watchdog tick, used by long-lived capsules to age
   * out stale state (timeouts, abandoned correlations, etc.).
   * Topic: `astrid.v1.watchdog.tick`.
   */
  export interface WatchdogTick {
    /** Wall-clock time of the tick (UNIX epoch milliseconds). */
    timestamp_ms: bigint;
  }

  /**
   * Warning emitted when a subscriber falls behind and the bus had to
   * drop messages. Subscribers can use this as a signal to drain or
   * resubscribe. Topic: `astrid.v1.event_bus.lagged`.
   */
  export interface EventBusLagged {
    /** Topic that lagged. */
    topic: string;
    /** Number of messages dropped. */
    dropped: bigint;
  }

  /**
   * Cooperative restart signal — the kernel asks long-lived capsules
   * to flush ephemeral state and re-arm. Topic: `system.v1.lifecycle.restart`.
   */
  export interface LifecycleRestart {
    /** Reason for the restart (e.g. `"config-reload"`, `"upgrade"`). */
    reason: string;
  }

  /**
   * A slash-command typed by a human in an uplink. The CLI capsule
   * publishes this when the user enters `/<command> [args]`. Routed
   * to the capsule that registered the command name via its manifest.
   * Topic: `cli.v1.command.execute`.
   */
  export interface CommandExecute {
    /** The command name (without the leading slash). */
    name: string;
    /** JSON-encoded arguments (parsed by the receiving capsule). */
    arguments: string;
    /** Session ID the command was issued in. */
    session_id: string;
  }

}

/** Types generated from the `tool` WIT interface. */
export namespace tool {
  /** Request to cancel in-flight tool executions. */
  export interface CancelRequest {
    call_ids: string[];
  }

  /**
   * Request asking a tool-providing capsule to enumerate its tools.
   * Topic: `tool.v1.request.describe`. Empty payload — every responder
   * returns its full tool list. Routed by the SDK macro from
   * `#[astrid::tool(...)]` attributes.
   */
  export interface DescribeRequest {
    /**
     * Correlation ID for the response. The capsule replies on
     * `tool.v1.response.describe.<correlation-id>`.
     */
    correlation_id: string;
  }

  /**
   * Response listing the tools a capsule provides.
   * Topic: `tool.v1.response.describe.<correlation-id>`.
   */
  export interface DescribeResponse {
    /** Must match the `correlation-id` from the originating request. */
    correlation_id: string;
    /** The capsule's exposed tools. */
    tools: types.ToolDefinition[];
  }

}

/** Types generated from the `user` WIT interface. */
export namespace user {
  /** A prompt typed by a human via an uplink. */
  export interface Prompt {
    /** The raw text input. */
    text: string;
    /** Session ID for conversation continuity. Defaults to `"default"`. */
    session_id: string;
    /**
     * Optional extra context (JSON-encoded) — e.g. attachments,
     * metadata, or per-turn flags the uplink wants to forward.
     */
    context?: string;
  }

}
